### ISSUE TITLE
problems with Venice sequence

### ISSUE THREAD

**Issue by DavidQiuChao** [xiaohuiben/fmmef-TIP-2020#2]
作者你好，我自己按照你提供的matlab版本的代码，做了Python版本的复现，我发现你提供的两个图像序列在matlab和Python 版上都没有问题，但是两个版本在venice 上出现了明显的缺陷，请问你有发现吗？

**Comment by xiaohuiben** [comment]
你好，感谢python复现！venice scene matlab跑是没问题的，如果有问题的话，你可以发我邮箱我看看效果：xiaohui102788@126.com

**Comment by DavidQiuChao** [comment]
> 你好，感谢python复现！venice scene matlab跑是没问题的，如果有问题的话，你可以发我邮箱我看看效果：[xiaohui102788@126.com](mailto:xiaohui102788@126.com)

作者你好，我已经将结果发你邮箱

**Comment by xiaohuiben** [comment]
收到！最近太忙，稍后恢复你，谢谢

**Comment by xiaohuiben** [comment]
你好，我试了我github上传的程序，直接用Venice sequence，是没有问题的，结果发你了

**Comment by DavidQiuChao** [comment]
我测试正常了，是我的测试图片序列的顺序没有按照由欠曝光到过曝光的顺序导致的
